### ISSUE TITLE
Styling status bar colours doesn't apply to indentation-indicator.

### ISSUE THREAD

**Issue by JesseLeite** [lee-dohm/indentation-indicator#16]
Styling status bar colours doesn't apply to indentation-indicator.

```less
.status-bar,
.status-bar a {
    color: @brown !important;
}
```

Results in:
![example](http://b3.ms/XmWn086VnYOk)

@lee-dohm, Is this my error?  Or is there a DOM rendering improvement that could be made?
